/*
 * ----------------------
 * FibonacciHeapNode.java
 * ----------------------
 * Class to be used by FibonacciHeap. In this case the 'key' will be the parameter
 * we want to store - so it will be correspondent to the '<T> data' represented
 * in the jgraph library.
 */
package Utilities;

/**
 *
 * @author nuno
 */
public class FibonacciHeapNode<T> {

    FibonacciHeapNode left;
    FibonacciHeapNode right;
    FibonacciHeapNode parent;
    FibonacciHeapNode child;
    boolean mark;
    int degree;
    int key;
    T data;

    public FibonacciHeapNode(T data, int k) {
        this.key = k;
        this.right = this;
        this.left = this;
        this.data = data;
    }

    public int getKey() {
        return key;
    }

    public T getData() {
        return data;
    }

    /*
     * Generated by NetBeans...
     */

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final FibonacciHeapNode<T> other = (FibonacciHeapNode<T>) obj;
        if (this.left != other.left && (this.left == null || !this.left.equals(other.left))) {
            return false;
        }
        if (this.right != other.right && (this.right == null || !this.right.equals(other.right))) {
            return false;
        }
        if (this.parent != other.parent && (this.parent == null || !this.parent.equals(other.parent))) {
            return false;
        }
        if (this.child != other.child && (this.child == null || !this.child.equals(other.child))) {
            return false;
        }
        if (this.degree != other.degree) {
            return false;
        }
        if (this.key != other.key) {
            return false;
        }
        if (this.data != other.data && (this.data == null || !this.data.equals(other.data))) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 97 * hash + (this.left != null ? this.left.hashCode() : 0);
        hash = 97 * hash + (this.right != null ? this.right.hashCode() : 0);
        hash = 97 * hash + (this.parent != null ? this.parent.hashCode() : 0);
        hash = 97 * hash + (this.child != null ? this.child.hashCode() : 0);
        hash = 97 * hash + this.degree;
        hash = 97 * hash + this.key;
        hash = 97 * hash + (this.data != null ? this.data.hashCode() : 0);
        return hash;
    }
}
